"""Read-only client for a student's own Canvas (bCourses) data via a
Personal Access Token.

This intentionally only supports the personal-access-token flow, not
OAuth/LTI: a PAT is generated by the student themselves in Canvas
(Account > Settings > "+ New Access Token"), is scoped to whatever that
student already has permission to see, and is revocable at any time from
the same page. This project never asks for a Canvas password -- only a
token supplied via the CANVAS_API_TOKEN environment variable, which is
never hardcoded, logged, or committed.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

import requests

if TYPE_CHECKING:
    from llama_index.core import Document

# No default host on purpose: Canvas is multi-tenant and every school runs
# its own instance (bcourses.berkeley.edu, ucommons.instructure.com,
# canvas.<school>.edu, ...). Guessing wrong would send a student's bearer
# token to the wrong server, so CANVAS_BASE_URL is required rather than
# defaulted.
REQUEST_TIMEOUT = 15
MAX_PAGES = 5  # safety cap on pagination follow, not expected to be hit for one student's data


class CanvasNotConfigured(RuntimeError):
    """Raised when CANVAS_API_TOKEN isn't set."""


@dataclass
class CanvasClient:
    base_url: str
    token: str

    @classmethod
    def from_env(cls) -> "CanvasClient":
        token = os.getenv("CANVAS_API_TOKEN")
        if not token:
            raise CanvasNotConfigured(
                "CANVAS_API_TOKEN is not set. Generate a personal access "
                "token in Canvas under Account > Settings > New Access "
                "Token, then set it as an environment variable (e.g. in a "
                "local .env file that is never committed)."
            )
        base_url = os.getenv("CANVAS_BASE_URL", "").rstrip("/")
        if not base_url:
            raise CanvasNotConfigured(
                "CANVAS_BASE_URL is not set. Set it to your school's Canvas "
                "host, e.g. https://bcourses.berkeley.edu or "
                "https://ucommons.instructure.com — it must match the site "
                "where the token was generated."
            )
        if not base_url.startswith("https://"):
            # A bearer token over plaintext HTTP would be sniffable.
            raise CanvasNotConfigured(f"CANVAS_BASE_URL must start with https:// (got {base_url!r})")
        return cls(base_url=base_url, token=token)

    def _get(self, path: str, params: dict[str, Any] | None = None) -> list[dict]:
        url = f"{self.base_url}{path}"
        headers = {"Authorization": f"Bearer {self.token}"}
        results: list[dict] = []
        pages = 0
        while url and pages < MAX_PAGES:
            resp = requests.get(url, headers=headers, params=params, timeout=REQUEST_TIMEOUT)
            resp.raise_for_status()
            payload = resp.json()
            results.extend(payload if isinstance(payload, list) else [payload])
            url = _next_page_url(resp.headers.get("Link"))
            params = None  # query params only apply to the first request; next-page URL already has them
            pages += 1
        return results

    def list_active_courses(self) -> list[dict]:
        return self._get("/api/v1/courses", params={"enrollment_state": "active", "per_page": 50})

    def list_assignments(self, course_id: int) -> list[dict]:
        return self._get(
            f"/api/v1/courses/{course_id}/assignments",
            params={"order_by": "due_at", "per_page": 50},
        )

    def list_announcements(self, course_ids: list[int]) -> list[dict]:
        if not course_ids:
            return []
        context_codes = [f"course_{cid}" for cid in course_ids]
        return self._get(
            "/api/v1/announcements",
            params={"context_codes[]": context_codes, "per_page": 25},
        )

    def fetch_documents(self) -> list["Document"]:
        """Pull this student's active courses, assignments, and recent
        announcements and turn them into LlamaIndex Documents, tagged
        scope="personal" so they're never mixed into the shared/public
        campus-info collection.

        llama_index is imported lazily so the HTTP/parsing logic above stays
        testable without pulling in the whole embedding stack."""
        from llama_index.core import Document

        courses = self.list_active_courses()
        documents: list[Document] = []

        for course in courses:
            course_id = course.get("id")
            course_name = course.get("name") or course.get("course_code") or f"course {course_id}"
            documents.append(
                Document(
                    text=f"Course: {course_name} (code: {course.get('course_code', 'n/a')}).",
                    metadata={"scope": "personal", "kind": "course", "course_id": course_id, "source": course_name},
                )
            )

            for assignment in self.list_assignments(course_id):
                due = assignment.get("due_at") or "no due date set"
                name = assignment.get("name", "Untitled assignment")
                points = assignment.get("points_possible")
                text = f"Assignment for {course_name}: '{name}', due {due}"
                if points is not None:
                    text += f", worth {points} points"
                text += "."
                documents.append(
                    Document(
                        text=text,
                        metadata={
                            "scope": "personal",
                            "kind": "assignment",
                            "course_id": course_id,
                            "source": f"{course_name} / {name}",
                        },
                    )
                )

        for announcement in self.list_announcements([c.get("id") for c in courses if c.get("id")]):
            title = announcement.get("title", "Untitled announcement")
            message = _strip_html(announcement.get("message", ""))
            documents.append(
                Document(
                    text=f"Announcement: '{title}'. {message}",
                    metadata={"scope": "personal", "kind": "announcement", "source": title},
                )
            )

        return documents


def _next_page_url(link_header: str | None) -> str | None:
    """Parse Canvas's RFC 5988 Link header for the 'next' page URL."""
    if not link_header:
        return None
    for part in link_header.split(","):
        segments = part.split(";")
        if len(segments) < 2:
            continue
        url_part = segments[0].strip()
        rel_part = segments[1].strip()
        if rel_part == 'rel="next"' and url_part.startswith("<") and url_part.endswith(">"):
            return url_part[1:-1]
    return None


def _strip_html(html: str) -> str:
    """Minimal tag stripping for announcement bodies -- good enough for
    embedding text, not meant to be a general HTML sanitizer."""
    text = re.sub(r"<[^>]+>", " ", html)
    return re.sub(r"\s+", " ", text).strip()
